name: 'saku-mail'
services:
  api:
    image: sakurarealm-docker.pkg.coding.net/sakurasite/major/saku-mail:latest
    ports:
      - "18080:80"
    restart: always
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - E:\mail\mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_USER=mail
      - MYSQL_PASSWORD=SakuraMail
      - MYSQL_DATABASE=mail
    ports:
      - "3306:3306"

volumes:
  mail: