name: 'saku-mail'
services:
  api:
    image: sakurarealm-docker.pkg.coding.net/sakurasite/major/saku-mail:latest
    ports:
      - "18080:80"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/constasj/mail/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_USER=mail
      - MYSQL_PASSWORD=SakuraMail
      - MYSQL_DATABASE=mail
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'mail', '-p$$MYSQL_PASSWORD' ]
      timeout: 20s
      retries: 10
    ports:
      - "37016:3306"