name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: sakurarealm-docker.pkg.coding.net
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sakurarealm-docker.pkg.coding.net/sakurasite/major/saku-mail:latest
          platforms: linux/amd64
  deploy:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://43.248.189.10:9443/api/stacks/webhooks/765bf92d-6fa0-49c9-bb6d-552d172de83e
          method: POST
