name: CODING.net代码同步
on:
    push
jobs:
    sync:
        name: 向CODING.net推送代码
        runs-on: ubuntu-latest
        steps:
            - name: 检出代码
              uses: actions/checkout@main
            - name: 向CODING推送
              uses: yesolutions/mirror-action@v0.7.0
              with:
                REMOTE: https://${{ secrets.CODING_USERNAME }}:${{ secrets.CODING_TOKEN }}@e.coding.net/sakurarealm/sakurasite/backend-api.git